### ISSUE TITLE
sequence of fields

### ISSUE THREAD

**Issue by bumblebee831** [besja/vfu.events#5]
Please change the sequence of the fields:

Form:
…
After ‚Land‘
# Beitragsstaffelung

…

**Comment by bumblebee831** [comment]
It's the field with the 4 options. (within speaker)

**Comment by besja** [comment]
@bumblebee831, give me please the right order of fields (with english names, if possible).  I actually don't understand it now.

**Comment by bumblebee831** [comment]
Lastname
Firstname
male/female
job
organisation
email
phone
street
number
zipcode
city
country
PRICING !!!
Participation
Accomodation
Dinner
Vegetarian food
intolerances
workshops
arrival by
comment

**Comment by besja** [comment]
ok, thank you
